# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/main.go
  binary: backup
  ldflags:
   - -s -w -X main.version={{.Version}}
  goos:
    - linux
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
archive:
  replacements:
    linux: Linux
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
